In [1]:
#preprocessing the dataset
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
d=pd.read_csv("C:\\Users\\ELCOT\\Documents\\house price data set.csv")

In [3]:
d.describe()

,id,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
count,1.462000e+04,14620.000000,14620.000000,14620.000000,14620.000000,1.462000e+04,14620.000000,14620.000000,14620.000000,14620.000000,...,14620.000000,14620.000000,14620.000000,14620.000000,14620.000000,14620.000000,14620.000000,14620.000000,14620.000000,1.462000e+04
mean,6.762821e+09,42604.538646,3.379343,2.129583,2098.262996,1.509328e+04,1.502360,0.007661,0.233105,3.430506,...,1970.926402,90.924008,122033.062244,52.792848,-114.404007,1996.702257,12753.500068,2.012244,64.950958,5.389322e+05
std,6.237575e+03,67.347991,0.938719,0.769934,928.275721,3.791962e+04,0.540239,0.087193,0.766259,0.664151,...,29.493625,416.216661,19.082418,0.137522,0.141326,691.093366,26058.414467,0.817284,8.936008,3.675324e+05
min,6.762810e+09,42491.000000,1.000000,0.500000,370.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,...,1900.000000,0.000000,122003.000000,52.385900,-114.709000,460.000000,651.000000,1.000000,50.000000,7.800000e+04
25%,6.762815e+09,42546.000000,3.000000,1.750000,1440.000000,5.010750e+03,1.000000,0.000000,0.000000,3.000000,...,1951.000000,0.000000,122017.000000,52.707600,-114.519000,1490.000000,5097.750000,1.000000,57.000000,3.200000e+05
50%,6.762821e+09,42600.000000,3.000000,2.250000,1930.000000,7.620000e+03,1.500000,0.000000,0.000000,3.000000,...,1975.000000,0.000000,122032.000000,52.806400,-114.421000,1850.000000,7620.000000,2.000000,65.000000,4.500000e+05
75%,6.762826e+09,42662.000000,4.000000,2.500000,2570.000000,1.080000e+04,2.000000,0.000000,0.000000,4.000000,...,1997.000000,0.000000,122048.000000,52.908900,-114.315000,2380.000000,10125.000000,3.000000,73.000000,6.450000e+05
max,6.762832e+09,42734.000000,33.000000,8.000000,13540.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,...,2015.000000,2015.000000,122072.000000,53.007600,-113.505000,6110.000000,560617.000000,3.000000,80.000000,7.700000e+06

In [4]:
df=d.dropna()

In [5]:
d.isnull().sum()

id                                       0
Date                                     0
number of bedrooms                       0
number of bathrooms                      0
living area                              0
lot area                                 0
number of floors                         0
waterfront present                       0
number of views                          0
condition of the house                   0
grade of the house                       0
Area of the house(excluding basement)    0
Area of the basement                     0
Built Year                               0
Renovation Year                          0
Postal Code                              0
Lattitude                                0
Longitude                                0
living_area_renov                        0
lot_area_renov                           0
Number of schools nearby                 0
Distance from the airport                0
Price                                    0
dtype: int64

In [6]:
x=pd.DataFrame(d.iloc[:,2:22].values)
y=d.iloc[:,22].values

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
sc = StandardScaler()

In [11]:
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [12]:
#Build the ANN model
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
classifier=Sequential()

In [14]:
#input layer,2 hidden layer,output layer
classifier.add(Dense(17,activation='relu'))
classifier.add(Dense(11,activation='relu'))
classifier.add(Dense(31,activation='relu'))
classifier.add(Dense(3,activation='linear'))

In [15]:
classifier.compile(optimizer='adam',loss='mse',metrics=['mse'])

In [16]:
#Train the model
classifier.fit(x_train,y_train,batch_size=10,epochs=25)

Epoch 1/25
1170/1170 [==============================] - 17s 7ms/step - loss: 374451273728.0000 - mse: 374451273728.0000
Epoch 2/25
1170/1170 [==============================] - 10s 9ms/step - loss: 95547645952.0000 - mse: 95547645952.0000
Epoch 3/25
1170/1170 [==============================] - 8s 7ms/step - loss: 60480880640.0000 - mse: 60480880640.0000
Epoch 4/25
1170/1170 [==============================] - 8s 7ms/step - loss: 52791476224.0000 - mse: 52791476224.0000
Epoch 5/25
1170/1170 [==============================] - 8s 7ms/step - loss: 47052165120.0000 - mse: 47052165120.0000
Epoch 6/25
1170/1170 [==============================] - 9s 7ms/step - loss: 42680553472.0000 - mse: 42680553472.0000
Epoch 7/25
1170/1170 [==============================] - 10s 8ms/step - loss: 39635202048.0000 - mse: 39635202048.0000
Epoch 8/25
1170/1170 [==============================] - 8s 7ms/step - loss: 37688307712.0000 - mse: 37688307712.0000
Epoch 9/25
1170/1170 [==============================] - 8s 7ms/step - loss: 36397748224.0000 - mse: 36397748224.0000
Epoch 10/25
1170/1170 [==============================] - 13s 11ms/step - loss: 35526717440.0000 - mse: 35526717440.0000
Epoch 11/25
1170/1170 [==============================] - 9s 8ms/step - loss: 34862858240.0000 - mse: 34862858240.0000
Epoch 12/25
1170/1170 [==============================] - 11s 9ms/step - loss: 34312599552.0000 - mse: 34312603648.0000
Epoch 13/25
1170/1170 [==============================] - 9s 7ms/step - loss: 33834317824.0000 - mse: 33834317824.0000
Epoch 14/25
1170/1170 [==============================] - 9s 8ms/step - loss: 33443475456.0000 - mse: 33443475456.0000
Epoch 15/25
1170/1170 [==============================] - 11s 10ms/step - loss: 33129562112.0000 - mse: 33129568256.0000
Epoch 16/25
1170/1170 [==============================] - 11s 9ms/step - loss: 32857806848.0000 - mse: 32857806848.0000
Epoch 17/25
1170/1170 [==============================] - 10s 9ms/step - loss: 32565813248.0000 - mse: 32565813248.0000
Epoch 18/25
1170/1170 [==============================] - 12s 10ms/step - loss: 32358545408.0000 - mse: 32358545408.0000
Epoch 19/25
1170/1170 [==============================] - 13s 11ms/step - loss: 32057309184.0000 - mse: 32057309184.0000
Epoch 20/25
1170/1170 [==============================] - 12s 10ms/step - loss: 31878365184.0000 - mse: 31878365184.0000
Epoch 21/25
1170/1170 [==============================] - 10s 9ms/step - loss: 31704199168.0000 - mse: 31704199168.0000
Epoch 22/25
1170/1170 [==============================] - 10s 8ms/step - loss: 31531200512.0000 - mse: 31531200512.0000
Epoch 23/25
1170/1170 [==============================] - 12s 10ms/step - loss: 31479756800.0000 - mse: 31479756800.0000
Epoch 24/25
1170/1170 [==============================] - 12s 10ms/step - loss: 31269746688.0000 - mse: 31269746688.0000
Epoch 25/25
1170/1170 [==============================] - 9s 8ms/step - loss: 31150696448.0000 - mse: 31150694400.0000

In [17]:
#Test the model
y_pred=classifier.predict(x_test)
y_pred=(y_pred>0.5)

92/92 [==============================] - 3s 9ms/step